name: Upstream Sync

# 权限配置
permissions:
  contents: write

# 触发条件：定时任务（每天0点执行） + 手动触发
on:
  schedule:
    - cron:  '0 0 * * *'   # cron表达式，表示每天UTC时间0点运行
  workflow_dispatch:       # 允许手动触发

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync with Upstream
    if: ${{ github.event.repository.fork }}  # 确保只在fork的仓库运行
    steps:
    - name: Checkout target repo
      uses: actions/checkout@v3

    - name: Sync Upstream
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
      with:
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_repo: liliMozi/openhanako   # 替换为原始仓库路径
        upstream_sync_branch: main                          # 原始仓库的分支
        target_sync_branch: main                            # 你fork仓库的目标分支
        test_mode: false
